runtime: python37

instance_class: F1
default_expiration: "30s"

entrypoint: gunicorn -b :$PORT -w 1 --threads 2 --disable-redirect-access-to-syslog main:app

automatic_scaling:
  max_concurrent_requests: 2
  max_instances: 1
  max_idle_instances: 1

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt

inbound_services:
- warmup

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "store_credentials.json"