from viur.core import conf, securityheaders
from viur.core.modules.file import thumbnailer

# ------------------------------------------------------------------------------
# General configuration
#

#conf["viur.disableCache"] = True
#conf["viur.debug.traceExternalCallRouting"] = True

conf["viur.file.hmacKey"] = b"f863e8a9dd7349b8e9cc18286d507911"   #fixme: should be generated by ViUR core?
conf["viur.file.derivers"] = {
	"thumbnail": thumbnailer
}

conf["derives"] = {
	"big": {
		"callee": "thumbnail",
		"group": "srcset",
		"width": 1920
	},
	"normal": {
		"callee": "thumbnail",
		"group": "srcset",
		"width": 900
	},
	"small": {
		"callee": "thumbnail",
		"group": "srcset",
		"width": 500
	}
}

# ------------------------------------------------------------------------------
# Language-specific configuration
#

#conf["viur.languageMethod"] = "url"
#conf["viur.availableLanguages"] = ["en", "de"]

# ------------------------------------------------------------------------------
# ViUR admin tool specific configurations
#

conf["admin.vi.name"] = "{{app_id}}"

# ------------------------------------------------------------------------------
# Content Security Policy
#

# Google Cloud Storage
securityheaders.addCspRule("img-src", "storage.googleapis.com", "enforce")

#GitHub Buttons
securityheaders.addCspRule("script-src", "buttons.github.io", "enforce")
securityheaders.addCspRule("connect-src", "api.github.com", "enforce")

# ------------------------------------------------------------------------------
# Server startup
#

from viur import core
import modules, render

#core.setDefaultLanguage("en") #set default language!
app = core.setup(modules, render)